baseURL: "https://utscience.github.io/science-blog/"
languageCode: "en-us"
title: "Utscience Blog"
theme: "PaperMod"

params:
  homeInfoParams:
    Title: "Welcome to Utscience Blog"
    Content: "A science blog powered by Hugo + PaperMod"
  ShowShareButtons: true
  ShowReadingTime: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  defaultTheme: auto
  disableThemeToggle: false
menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 10
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 20
