baseURL: "https://utscience.github.io/science-blog/"
languageCode: "en-us"
title: "Science Daily"
theme: "PaperMod"

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 2

params:
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
